#ifndef LINKDEFINE
#define LINKDEFINE

#include <fltKernel.h>

#define	DEVICE_NAME			L"\\Device\\YJHDBG"
#define LINK_NAME			L"\\DosDevices\\YJHDBG"


#define IOCTL_GetServiceTableBase		   CTL_CODE(FILE_DEVICE_UNKNOWN,0x900,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_GetSSDTAddressByIndex		   CTL_CODE(FILE_DEVICE_UNKNOWN,0x901,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_GetW32pServiceTable		   CTL_CODE(FILE_DEVICE_UNKNOWN,0x902,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_GetSSSDTAddressByIndex	   CTL_CODE(FILE_DEVICE_UNKNOWN,0x903,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_Draw						   CTL_CODE(FILE_DEVICE_UNKNOWN,0x904,METHOD_BUFFERED,FILE_ANY_ACCESS) 


#define IOCTL_Read						   CTL_CODE(FILE_DEVICE_UNKNOWN,0x905,METHOD_BUFFERED,FILE_ANY_ACCESS) 
#define IOCTL_Write						   CTL_CODE(FILE_DEVICE_UNKNOWN,0x906,METHOD_BUFFERED,FILE_ANY_ACCESS) 
#define IOCTL_InputRWPid                   CTL_CODE(FILE_DEVICE_UNKNOWN,0x907,METHOD_BUFFERED,FILE_ANY_ACCESS) 
#define IOCTL_GetRWBase					   CTL_CODE(FILE_DEVICE_UNKNOWN,0x908,METHOD_BUFFERED,FILE_ANY_ACCESS) 



#define IOCTL_PASSPG				CTL_CODE(FILE_DEVICE_UNKNOWN,0x909,METHOD_BUFFERED,FILE_ANY_ACCESS) 
#define IOCTL_UNPASSPG				CTL_CODE(FILE_DEVICE_UNKNOWN,0x910,METHOD_BUFFERED,FILE_ANY_ACCESS) 
#define IOCTL_INIT_TABLE			CTL_CODE(FILE_DEVICE_UNKNOWN,0x911,METHOD_BUFFERED,FILE_ANY_ACCESS) 
#define IOCTL_INIT_HOOK_TABLE		CTL_CODE(FILE_DEVICE_UNKNOWN,0x912,METHOD_BUFFERED,FILE_ANY_ACCESS) 
#define IOCTL_ADD_DEBUGGER			CTL_CODE(FILE_DEVICE_UNKNOWN,0x913,METHOD_BUFFERED,FILE_ANY_ACCESS) 
#define IOCTL_DESTORY_PROTECT		CTL_CODE(FILE_DEVICE_UNKNOWN,0x914,METHOD_BUFFERED,FILE_ANY_ACCESS) 


#define IOCTL_HARD_BREAK_THREAD		CTL_CODE(FILE_DEVICE_UNKNOWN,0x915,METHOD_BUFFERED,FILE_ANY_ACCESS) 
#define IOCTL_HARD_THREAD_COUNT		CTL_CODE(FILE_DEVICE_UNKNOWN,0x916,METHOD_BUFFERED,FILE_ANY_ACCESS) 
#define IOCTL_BREAK_ADDRESS         CTL_CODE(FILE_DEVICE_UNKNOWN,0x917,METHOD_BUFFERED,FILE_ANY_ACCESS)    


#endif